version: '3.8'
services:
  blockchain-listener:
    build:
      context: ./
      target: blockchain-listener
    env_file: ./.env
    environment:
      WARDEN_API_URL: ${WARDEN_API_URL}
      WARDEN_RPC_URL: ${WARDEN_RPC_URL}
      WARDEN_POLLING_INTERVAL_MSEC: ${WARDEN_POLLING_INTERVAL_MSEC}
      WARDEN_CHAIN_ID: ${WARDEN_CHAIN_ID}
      WARDEN_CHAIN_PREFIX: ${WARDEN_CHAIN_PREFIX}
      WARDEN_SIGNER_MNEMONIC: ${WARDEN_SIGNER_MNEMONIC}
      WARDEN_SIGNER_DERIVATION_PATH: ${WARDEN_SIGNER_DERIVATION_PATH}
      WARDEN_FORDEFI_KEYCHAIN_ID: ${WARDEN_FORDEFI_KEYCHAIN_ID}
      BROKER_CONNECTION_STRING: ${BROKER_CONNECTION_STRING}
      BROKER_NEW_KEY_QUEUE_NAME: ${BROKER_NEW_KEY_QUEUE_NAME}
      BROKER_NEW_SIGNATURE_QUEUE_NAME: ${BROKER_NEW_SIGNATURE_QUEUE_NAME}
      BROKER_RECONNECT_MSEC: ${BROKER_RECONNECT_MSEC}
      BROKER_QUEUE_PREFETCH: ${BROKER_QUEUE_PREFETCH}

  message-handler:
    build:
      context: ./
      target: message-handler
    env_file: ./.env
    environment:
      AWS_KMS_REGION: ${AWS_KMS_REGION}
      AWS_KMS_FORDEFI_CLIENT_PK_KEY_ID: ${AWS_KMS_FORDEFI_CLIENT_PK_KEY_ID}
      WARDEN_API_URL: ${WARDEN_API_URL}
      WARDEN_RPC_URL: ${WARDEN_RPC_URL}
      WARDEN_POLLING_INTERVAL_MSEC: ${WARDEN_POLLING_INTERVAL_MSEC}
      WARDEN_CHAIN_ID: ${WARDEN_CHAIN_ID}
      WARDEN_CHAIN_PREFIX: ${WARDEN_CHAIN_PREFIX}
      WARDEN_SIGNER_MNEMONIC: ${WARDEN_SIGNER_MNEMONIC}
      WARDEN_SIGNER_DERIVATION_PATH: ${WARDEN_SIGNER_DERIVATION_PATH}
      BROKER_CONNECTION_STRING: ${BROKER_CONNECTION_STRING}
      BROKER_NEW_KEY_QUEUE_NAME: ${BROKER_NEW_KEY_QUEUE_NAME}
      BROKER_SIGNATURE_STATUS_QUEUE_NAME: ${BROKER_SIGNATURE_STATUS_QUEUE_NAME}
      BROKER_RECONNECT_MSEC: ${BROKER_RECONNECT_MSEC}
      BROKER_QUEUE_PREFETCH: ${BROKER_QUEUE_PREFETCH}
      BROKER_CONSUMER_RETRY_ATTEMPTS: ${BROKER_CONSUMER_RETRY_ATTEMPTS}
      FORDEFI_ACCESS_TOKEN: ${FORDEFI_ACCESS_TOKEN}
      FORDEFI_API_ENDPOINT: ${FORDEFI_API_ENDPOINT}
      FORDEFI_UUIDV5_NAMESPACE: ${FORDEFI_UUIDV5_NAMESPACE}

  webhooks:
    build:
      context: ./
      target: webhooks
    env_file: ./.env
    environment:
      FORDEFI_PUBLIC_KEY: ${FORDEFI_PUBLIC_KEY}
      WEBHOOK_PORT: ${WEBHOOK_PORT}
      BROKER_CONNECTION_STRING: ${BROKER_CONNECTION_STRING}
      BROKER_SIGNATURE_STATUS_QUEUE_NAME: ${BROKER_SIGNATURE_STATUS_QUEUE_NAME}
      BROKER_RECONNECT_MSEC: ${BROKER_RECONNECT_MSEC}
      BROKER_QUEUE_PREFETCH: ${BROKER_QUEUE_PREFETCH}
