export interface Env {
  WARDEN_RPC_URL: string;
  WARDEN_API_URL: string;
  WARDEN_POLLING_INTERVAL_MSEC: number;
  WARDEN_CHAIN_ID: string;
  WARDEN_CHAIN_PREFIX: string;
  WARDEN_SIGNER_MNEMONIC: string;
  WARDEN_SIGNER_GAS: number;
  WARDEN_SIGNER_GAS_FEE_AMOUNT: number;
  WARDEN_FORDEFI_KEYCHAIN_ID: string;
  WARDEN_SIGNER_FEE_DENOM: string;

  BROKER_CONNECTION_STRING: string;
  BROKER_NEW_KEY_QUEUE_NAME: string;
  BROKER_NEW_SIGNATURE_QUEUE_NAME: string;
  BROKER_RECONNECT_MSEC: number;
  BROKER_QUEUE_PREFETCH: number;
  BROKER_MAX_RECONNECT_ATTEMPTS: number;
  BROKER_ERROR_EVENT_RESET_PERIOD_MS: number;
}
