export interface Env {
  AWS_KMS_REGION: string;
  AWS_KMS_FORDEFI_CLIENT_PK_KEY_ID: string;

  WARDEN_RPC_URL: string;
  WARDEN_API_URL: string;
  WARDEN_POLLING_INTERVAL_MSEC: number;
  WARDEN_CHAIN_ID: string;
  WARDEN_CHAIN_PREFIX: string;
  WARDEN_SIGNER_MNEMONIC: string;
  WARDEN_SIGNER_GAS: number;
  WARDEN_SIGNER_GAS_FEE_AMOUNT: number;
  WARDEN_SIGNER_FEE_DENOM: string;

  BROKER_CONNECTION_STRING: string;
  BROKER_NEW_KEY_QUEUE_NAME: string;
  BROKER_NEW_SIGNATURE_QUEUE_NAME: string;
  BROKER_SIGNATURE_STATUS_QUEUE_NAME: string;
  BROKER_RECONNECT_MSEC: number;
  BROKER_QUEUE_PREFETCH: number;
  BROKER_CONSUMER_RETRY_ATTEMPTS: number;

  FORDEFI_ACCESS_TOKEN: string;
  FORDEFI_API_ENDPOINT: string;
  FORDEFI_UUIDV5_NAMESPACE: string;
  FORDEFI_API_USER_NAME: string;
}
