---
name: Release images
on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "Service"
        required: true
        type: choice
        options:
          - blockchain-listener
          - message-handler
          - webhooks
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

jobs:
  release:
    name: Release ${{inputs.service_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.REGISTRY }}/${{ inputs.service_name }}
          tags: |
            type=semver,pattern={{raw}}
            type=sha,format=short,prefix=
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: ${{ inputs.service_name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SERVICE=${{ inputs.service_name }}
            COMMIT=${{ steps.meta.sha }}
            VERSION=${{ steps.meta.semver }}
